### ISSUE TITLE
shodan.exception.APIError: Please upgrade your API plan to use filters or paging.

### ISSUE THREAD

**Issue by mremployee** [pielco11/fav-up#2]
It is giving me,

```
Mask-IP: 104.26.15.225
Mask-ISP: CLOUDFLARENET
Favicon Hash: -1690082520
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    shodanSearch(favhash)
  File "main.py", line 31, in shodanSearch
    results = shodan.search(f"http.favicon.hash:{favhash}")
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/shodan/client.py", line 498, in search
    return self._request('/shodan/host/search', args)
  File "/home/runner/.local/share/virtualenvs/python3/lib/python3.7/site-packages/shodan/client.py", line 321, in _request
    raise APIError(error)
shodan.exception.APIError: Please upgrade your API plan to use filters or paging.
```
> I don't have any paid membership 

Do I need a paid membership in order to use this?

**Comment by pielco11** [comment]
`http.favicon.hash:0xxxxx` is a filter, and as such `Query credits` are required. More at https://help.shodan.io/the-basics/credit-types-explained
