### ISSUE TITLE
got an unexpected keyword argument 'use_external_data'

### ISSUE THREAD

**Issue by mastercho** [pielco11/fav-up#21]
I'm getting following error

python favUp.py

```
Traceback (most recent call last):
  File "/root/Tools/fav-up/favUp.py", line 299, in <module>
    FavUpApp = FavUp(show=True)
  File "/root/Tools/fav-up/favUp.py", line 43, in __init__
    self.ua = UserAgent(use_external_data=True, cache_path=self.ua_json_location)
TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'use_external_data'

```

all from requirements folder is installed and using Python 3.10.12

**Comment by pielco11** [comment]
Hi,

the issue was with an outdated version of the `FakeUserAgent` module.

It's expected to be working now.
